### ISSUE TITLE
Using it without prefix

### ISSUE THREAD

**Issue by Sir-Will** [pie-flavor/Boop#2]
hey,
I removed the prefix but it still uses `@` as prefix instead of none. 
Would be great if it would be possible to use it without prefix.

**Comment by pie-flavor** [comment]
There are no plans to implement this functionality at this time.
If there is no prefix, it becomes very easy to accidentally boop someone simply by talking about them.
Not to mention that due to the API, every message would match because it doesn't know how to distinguish the playername prefix from the message itself.
